### ISSUE TITLE
course-HW 2 Solutions; Chapter 3 (p. 61); #1;

### ISSUE THREAD

**Issue by skaunov** [thor314/uncloak#23]
Will <https://github.com/thor314/uncloak/tree/main/courses/rust%20cryptography%20engineering> continue to sync with <https://uncloak.org/courses/rust+cryptography+engineering>? Wanted to raise the discussion as a PR, but found no file for "course-HW 2 Solutions".

I'm quite sure there is a typo at point "How many possible blocks are there? ": the last digit should be "4" to get 2^64.

And I also suspect that transition from entries to bits lost the same digit "4" in the end, so it should be 2^144 * _2^64_ = 2^208; and consequentially last number become 2^205.

**Comment by skaunov** [comment]
Also at Uncloak.org Session 2 Notes and HW2 solutions are a bit out of sync: HW2 contains "#5;" for Ch4, but Session 2 Notes lacks it.

**Comment by thor314** [comment]
PR #26 fixes this. Thanks!
