### ISSUE TITLE
session #6 notes: wrong link, typo

### ISSUE THREAD

**Issue by skaunov** [thor314/uncloak#39]
see https://uncloak.org/courses/rust+cryptography+engineering/course-2022-01-06+Session+6+Notes
# wrong link
> discussed last week in the context of the [subtle](https://people.csail.mit.edu/nickolai/papers/lazar-cryptobugs.pdf) crate 

links again to the paper that is discussed 

# typo
in the _wild_?
> the following links for several examples in the wind

**Comment by thor314** [comment]
Thanks! Fixed.
